### ISSUE TITLE
Create a python script produces a range of VR input files out of the SA file and a template input

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/virtual_rainforest#241]
This script, building on the minimal one defined in #240 , will load the SA file, a template config file for VR and create a collection of also valid configuration files differing from one another in the value of just one (or more) parameters. Specific tasks that this script will perform are:

- [ ] Read both files (validating the SA one; see #240)
- [ ] Verify that all parameters to vary defined in the SA file are indeed in the template config file
   - NOTE: [As there might not be a single configuration file](https://virtual-rainforest.readthedocs.io/en/latest/virtual_rainforest/core/config.html#configuration-files), but a collection of them, it might be necessary to run the configuration part of VR first in order to get a single config file to use as template.
- [ ] Create the set of new parameters following the procedure described in #240
- [ ] For each set, create a new config file where the relevant parameters are replaced by the new values
- [ ] An auxiliary CSV file will be created summarising the parameter sweep, eg.:

| Config file | parameter_1 | parameter_2 |
| -----------| -------------|--------------|
| madagascar01.toml | 15 | 20 |
| madagascar02.toml | 15 | 30 |
| madagascar03.toml | 15 | 40 |
| madagascar04.toml | 20 | 20 |
| madagascar05.toml | 20 | 30 |
| madagascar06.toml | 20 | 40 |
| madagascar07.toml | 25 | 20 |
| madagascar08.toml | 25 | 30 |
| madagascar09.toml | 25 | 40 |

The naming convention of the new config files will be such that they can be easily ingested by the submission script for the Imperial's HPC (see #242 ).

Question:
- How would be best to handle the case of configuration spread across multiple config files?

**Comment by jacobcook1995** [comment]
I think initialising a `Config` and then using the methods defined there might be the simplest way of combining the config files (including the validation step `validate_config`).

I would mainly recommend this as the configuration schema define default values for a lot of parameters, which get added into the config when the validation gets carried out. This means we usually won't be using config files that define every parameter as in a lot of cases we will just want to use the default values. I can't see an issue in us generating full config files for the purpose of parameter sensitivity analysis though, if that turns out to be simpler.
