### ISSUE TITLE
In config files, paths are relative to CWD

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/virtual_rainforest#264]
Really, they need to be relative to the config file itself, otherwise you have to `cd` to the correct dir before invoking `vr_run` in order to make things work as expected.

I'll give an example. Currently I have a config file with this in:

```toml
[[core.data.variable]]
file = "dummy_data/ERA5_land_dummy.nc"
var_name = "air_temperature_ref"
```

The `ERA_land_dummy.nc` file is in the same directory as the config file, but I also have to put in the name of the subfolder (`dummy_data`) in order for VR to be able to find it. Note that if `vr_run` is invoked from a different folder (e.g. the user runs `vr_run some/parent/folders/dummy_data`) it won't work at all.

This makes it quite annoying to share datasets with people, as they will either have to a) change a bunch of paths in the config files or b) make sure the path on their machine (either relative or absolute) is the same. Both of these options are a bit grim.

This is of particular interest to me as I want to be able to invoke `vr_run` from an arbitrary location as part of my work on #239.

**Comment by davidorme** [comment]
This doesn't negate this issue, but one thing about #239 is exactly which "variables" the first draft of the SA should target. We discussed this a bit with @dalonsoa.

IIRC, Diego had primarily been thinking about different 'data' variables: things that we might expect to provide some kind of array to provide data on different axes (spatial / temporal / vertical etc). I think we'd been thinking of sensitivity to varying 'constants'. Now 'constants' is a dubious name here because it includes genuine physical constants but also a bunch of empirically estimated values that are constant within a particular `vr_run`. Those would be set be modifying the constants configuration (hence the recent work on the system set up in #258 and subsequent rollout to modules).

**Comment by davidorme** [comment]
Sorry - wrong end of wrong stick. I thought you were trying to vary the input netcdf files.
